name: baby_watcher
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  shared_preferences: ^2.5.2
  flutter_svg: ^2.0.17
  pinput: ^5.0.1
  url_launcher: ^6.3.1
  video_player: ^2.9.3
  appinio_video_player: ^1.2.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/language/
    - assets/icons/
    - assets/images/


  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Italic-VariableFont_wght.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Mulish-VariableFont_wght.ttf
          weight: 100